project:
  type: website

website:
  title: "ISSS608 - Sherinah Rashid"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3A"
          href: "Hands-on_Ex/Hands-on_Ex03A/Hands-on_Ex03A.html"
        - text: "Hands-on Exercise 3B"
          href: "Hands-on_Ex/Hands-on_Ex03B/Hands-on_Ex03B.html"
        - text: "Hands-on Exercise 4A"
          href: "Hands-on_Ex/Hands-on_Ex04A/Hands-on_Ex04A.html"
        - text: "Hands-on Exercise 4B"
          href: "Hands-on_Ex/Hands-on_Ex04B/Hands-on_Ex04B.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
    - text: "In-Class Exercises"
      menu: 
        - text: "In-Class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-Class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-Class Exercise 7"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
    - text: "Take-Home Exercises"
      menu: 
        - text: "Take Home Exercise 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Take Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
        - text: "Take Home Exercise 3"
          href: "Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

