project:
  type: website

website:
  title: "ISSS608 - Sherinah Rashid"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3.1"
          href: "Hands-on_Ex/Hands-on_Ex031/Hands-on_Ex031.html"
        - text: "Hands-on Exercise 3.2"
          href: "Hands-on_Ex/Hands-on_Ex032/Hands-on_Ex032.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
    - text: "In-Class Exercises"
      menu: 
        - text: "In-Class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-Class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-Class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
    - text: "Take-Home Exercises"
      menu: 
        - text: "Take Home Exercise 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Take Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

